### ISSUE TITLE
RudderStack referrer bug 

### ISSUE THREAD

**Issue by jinouyang** [near/near-discovery#884] opened 2023-12-11 23:37 UTC
**Describe the bug**
Both @TiffanyGYJ  and @thisisjoshford are interested in knowing the user journey (how they got from one page to another). This requires `referrer` and `initial_referrer` to be correctly tracked with RudderStack. Until this is fixed, the measurement on user journey will be blocked. My understanding is that we plan to do more data driven analytics in the new year. In that case, this fix should be a priority in January.

**Expected behavior**
- referrer should record the previous page tab_url 
- initial_referrer should record the initial referrer of the current page in the browser
See documentation here: https://www.rudderstack.com/docs/event-spec/standard-events/common-fields/

**Comment by charleslavon** [comment] 2024-01-10 15:23
@jinouyang Closing this as not a bug. The referrer properties are automatically collected by Rudderstack, with data coming from a browser's document object itself. There are valid cases when this value is empty, such as when a user navigates to the page directly (not through a link, but, for example, by using a bookmark such as a homescreen icon on a mobile device.)

**Comment by charleslavon** [comment] 2024-01-10 19:46
i've found an alternate path forward.

**Comment by s-n-park** [comment] 2024-01-24 00:38
Testing initial referrer vs. referrer does appear that this might be buggy

Here's a specific [example](https://docs.google.com/spreadsheets/d/1g30_HVe5NYY_gjGN_RfQrXuYAzp7BGGae_YhO45JakE/edit#gid=1500126817) session, where we can see page changing, but referrer is set to $direct along with initial referrer (I usually would expect this to change).

Als looking across the data ([query](https://4221960800361869.9.gcp.databricks.com/sql/editor/185da3c3-6518-4fc5-8241-14364ad15e2b?o=4221960800361869) - I excluded when the URL matched the first URL of the session) it appears that Initial Referrer and Ref might be the same sometimes as high as 80% 

![Screenshot 2024-01-19 at 8 43 54 AM](https://github.com/near/near-discovery/assets/146785798/50f03b12-74c5-4a7f-9e6a-50429cdbb152)

**Comment by jinouyang** [comment] 2024-03-04 20:36
Reopening since we was not able to fully resolve the issue: when the page is not full reloaded, `referrer` won't be accurate. Potential solution discussed with @charleslavon : storing the last url in local storage or cookie

Context: this is flagged as a high priority by Founder Success lead.

**Closed** 2024-03-05 19:26 UTC
Labels: bug
