### ISSUE TITLE
The input border on the dev.near.org search bar extends past it's container

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1180] opened 2024-05-16 13:55 UTC
<img width="412" alt="Screen Shot 2024-05-16 at 9 52 02 AM" src="https://github.com/near/near-discovery/assets/1915116/f3c38810-7ebb-4b51-82ab-f9fa165d59ee">

Expected: The input focus and type behavior styles should match the current near.org.
<img width="259" alt="Screen Shot 2024-05-16 at 9 55 03 AM" src="https://github.com/near/near-discovery/assets/1915116/d94a227b-c3ba-434a-887a-24328756f978">

**Comment by calebjacob** [comment] 2024-05-21 15:17
I'm not able to reproduce the bug. That's definitely a strange screenshot. I'm going to close this for now and we can re-open if we see this issue appear again.

**Closed by calebjacob** 2024-05-21 15:17 UTC
Labels: bug
