### ISSUE TITLE
Search dropdown does not close after clicking on a search result

### ISSUE THREAD

**Issue by Patrick1904** [near/near-discovery#795] opened 2023-11-02 10:43 UTC
Issues:

1. Search does not close after clicking on a search result
2. Search does not close when clicking outside of the dropdown

<img width="802" alt="Screen Shot 2023-11-02 at 11 42 29 AM" src="https://github.com/near/near-discovery/assets/24921205/1772fed8-6452-4262-97ea-7dc584b6854a">

**Comment by charleslavon** [comment] 2023-11-13 18:14
duplicate of https://github.com/near/near-discovery/issues/807

**Closed by charleslavon** 2023-11-13 18:14 UTC
Labels: bug
