### ISSUE TITLE
P5 [NEARCON] Give ability for users to hide posts/comment if not found violating but undesirable

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#423] opened 2023-09-15 10:37 UTC
Description

Give ability for users to hide posts or comment at any point in time whenever they see it (e.g. first time seeing the content or after report action https://pagodaplatform.atlassian.net/browse/ROAD-319 …). The purpose of this feature is to improve feed content of users. Once selected, the content they have decided to hide will not be visible anymore to the user. (At a later stage we will also use that data to connect and propose further filtering option like “Would you like to hide all content related to #politics?“)

Potential Design/Surface

- The option will appear next to a post and comment anywhere on [near.org](http://near.org/) (feed etc.)

- It will also appear at the end of the reporting flow (https://pagodaplatform.atlassian.net/browse/ROAD-279)

- Finally, if the content was reported but “ignored“ by our moderation team, we will also provide this as an option to our users  (https://pagodaplatform.atlassian.net/browse/ROAD-279)

NB: Send back end data and look for commonalities (string/content score) and propose further filtering

![Image](https://github.com/near/near-discovery/assets/5955639/63792b68-a879-4768-9fe4-e3f0102a2f25)

**Comment by tidus974** [comment] 2023-09-15 10:39
Posting past comments as well: https://pagodaplatform.atlassian.net/browse/ROAD-346?focusedCommentId=37339

**Comment by charleslavon** [comment] 2023-09-27 14:01
@tidus974 can this be closed as a duplicate of the overall content reporting flow work [here](https://github.com/near/near-discovery/issues/393)?

**Comment by tidus974** [comment] 2023-09-27 14:19
Duplicate

**Closed** 2023-09-27 14:19 UTC
